# Файл docker-compose.yml

# Версия docker-compose
version: '3'

# Перечень volume
volumes:
  sqlite_data:

services:


  backend:

    build: ./commands/
    volumes:
      - sqlite_data:/data
    ports:
      - 8000:8000