version: '3'

volumes:
  pgdbdata: null

services:
  pgdb:
    image: postgres:13.10
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    container_name: pgdb
    volumes:
      - pgdbdata:/var/lib/postgresql/data/
  django:
    build: .
    container_name: django
    depends_on:
      - pgdb
    ports:
      - 8000:8000